import os
import pandas as pd
import requests
import sqlite3
import json
import aisuite as ai
# %%
# instantiates the client
client = ai.Client()

# function gets the schema of the sales table from SQLite database
def get_schema(db_path : str)-> str:
  """
  Return the 'sales' table schema that need to use by agent.

  """
  con = sqlite3.connect(db_path)
  cur = con.cursor()
  cur.execute("PRAGMA table_info(sales)")
  rows = cur.fetchall()
  con.close()
  return ("Table name: sales\n"
          +"\n".join([f"{r[1]} ({r[2]})" for r in rows])
  )
# %%
# function executes the SQL query and return the result as a pandas DataFrame
def execute_query(query: str,db_path: str):
  """
  Execute any SELECT over the 'sales' table.
  Return the result as a pandas DataFrame.
  """
  edited_query = (
      query.replace("```sql","")
      .replace("```","")
      .strip()
      )  #.removeprefix("```sql").removesuffix("```")
  print(edited_query)
  con = sqlite3.connect(db_path)
  try:
    return pd.read_sql_query(edited_query,con)
  except Exception as e:
    return pd.DataFrame({"error" : [str(e)]})
  finally:
    con.close()

# function gets the weather information for a given city using OpenWeatherMap API

def get_weather(city_name: str):
    weather_api_key = os.environ.get("WEATHER_API_KEY")
    # It's better to pass the API key as an argument or use an environment variable
    url = f"https://api.openweathermap.org/data/2.5/weather?q={city_name}&appid={weather_api_key}"

    try:
        # 1. Execute the request
        response = requests.get(url)

        # 2. Check if the HTTP request itself failed (e.g., 404 or 401)
        response.raise_for_status()

        # 3. Parse the data
        data = response.json()

        # Extract info safely
        degree_celsius = round(data['main']['temp'] - 273.15)
        weather = data['weather'][0]['main']
        description = data['weather'][0]['description']
        feels_like_temp = round(data['main']['feels_like'] - 273.15)

        # 4. Return a plain string (which is JSON serializable)
        return (
            f"The current temperature of {city_name} is {degree_celsius}°C. "
            f"The weather is {weather} with {description}. "
            f"It feels like {feels_like_temp}°C."
        )

    except Exception as e:
        return f"Error: Could not retrieve weather for {city_name}. Details: {str(e)}"

# Agent will call this function and grabs weather information for the city.

def get_temperature(city_name: str,model: str) -> str:
  #city_name = input("Enter the city name: ").strip()
  Prompt = f""" You are a weather agent who gets the weather for the {city_name} asked by the user."""
  messages = [
    {"role": "system","content": "Always respond in british english."},
    {"role": "user","content": Prompt}
  ]
  response = client.chat.completions.create(
      model=model,
      messages=messages,
      tools=[get_weather],
      max_turns = 3,
      temperature = 1.0
  )

  return response.choices[0].message.content

# function generates SQL query based on user question and database schema using LLM

def sql_generator(question: str,schema: str,model: str,db_path: str) -> str:

    Prompt = f""" You are a SQL helper. Given the schema of the database table 'sales' and question, respond with SQL query only to answer it.

    Schema =
    {schema}

    User Question =
    {question}

    """
    response = client.chat.completions.create(
        model = model,
        messages = [{'role':'user','content': Prompt}],
        temperature = 1.0

    )
    return response.choices[0].message.content.strip()

# this agent reviews the initial sql query generated by sql_generator and provides feedback including improved query if required.
def sql_reviewer(
    question: str,
    schema: str,
    query_response: str,
    model: str,
    db_path: str
) -> tuple[str,str]:
    Prompt = f""" You are a sql reviewer. Given the schema of the database table 'sales',question and Initial query response,
    review the initial query and provide feedback on the query. If it needs improvement to answer user question provide improved query
    otherwise return the same query.
    Returns (feedback,improved_query).
    schema =
    {schema}
    User Question =
    {question}
    Initial Query Response =
    {query_response}

    Return STRICT JSON with two fields:
    {{
    "feedback": "<1-3 sentences explaining the gap or confirming correctness>",
    "reviewed_sql": "<final SQL to run>"
    }}
    """
    response = client.chat.completions.create(
        model = model,
        messages= [{'role':'user','content':Prompt}],
        temperature = 1.0
    )
    #print(response.choices[0].message.content.strip())

    reviewed_sql = response.choices[0].message.content.strip()

    try:
      reply = json.loads(reviewed_sql)
      feedback = reply['feedback']
      improved_query = reply['reviewed_sql']
      #print(f'Feedback: {feedback}')
      #print(f'Improved Query: {improved_query}')
    except Exception:
      Feedback: {reviewed_sql.strip()}
      reviewed_sql.strip() == query_response

    return feedback,improved_query

# This orcherstrates the entire SQL generation to resukt workflow.

def sql_agent_work_flow(question: str,db_path: str,model: str):
  #get_temperature(city_name="Sassenheim",model='openai:gpt-4o-mini')
  #question = input("Enter your question: ").strip()
  schema = get_schema(db_path)
  query_response = sql_generator(question,schema,model,db_path)
  result = execute_query(query_response,db_path)
  feedback,improved_query= sql_reviewer(question,schema,query_response,model,db_path)
  improved_result = execute_query(improved_query,db_path)
  return improved_result


# This is the main orcherstrator agent which routes the question to appropriate agent based on the category of the questions.

def Agentic_AI_orchestrator(user_prompt: str,db_path: str,model: str):
  question = user_prompt
  routing_prompt = f""" You are a routing agent who analyzes the user {question} and determine the next step in this workflow.
                    Analyze the user's question and categorize it.

                   EXAMPLES:
                  User: 'What is the temperature in London?'
                  Response: CATEGORY: WEATHER | SUBJECT: London

                  User: 'Show me the top 5 customers by sales.'
                  Response: CATEGORY: SQL | SUBJECT: None

                  User: 'Give the most expensive product sold.'
                  Response: CATEGORY: SQL | SUBJECT: None

                  User: 'Is it going to rain today in London?'
                  Response: CATEGORY:wikipedia_search | SUBJECT: London

                  User: 'How are you today?'
                  Response: CATEGORY: OTHER | SUBJECT: None

                  User: 'What is deep learning?'
                  Response: CATEGORY: OTHER | SUBJECT: None


              User: "{question}"
              Response:
              Do not respond with anything else.
                    """
  print(f'Please wait thinking for better response .....')
  routing_response = client.chat.completions.create(
      model = model,

      messages = [
          {"role": "system", "content": "You are a concise assistant. If asked a yes/no question, answer only with Yes or No followed by a short reason."},
          {'role':'user','content':routing_prompt}],
      temperature = 1.0
  )
  got_response = routing_response.choices[0].message.content.strip()
  #print(got_response)
  #print(f'Please wait thinking for better response: ')
  try:
    if 'WEATHER' in got_response:
      city_name = got_response.split('SUBJECT:')[-1].strip()

      return get_temperature(city_name=city_name,model=model)
    elif 'SQL' in got_response:
      return sql_agent_work_flow(question,db_path,model)
    elif 'OTHER' in got_response:
        general_response = client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": question}]
            )
        return general_response.choices[0].message.content.strip()
    else:
      return f'I cannot answer this question'

  except Exception as e:
    return f"Error has occured: {e}"

